version: 2
jobs:
  build:
    type: approval
    branches:
      only:
        - master
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r ./requirements.txt -t ./src
            pip install ./vrchat-api-python -t ./src
      - run:
          name: Compress src/
          command: |
            apk add zip
            chmod 444 ./* -R
            zip -r src src
            ls
      - store_artifacts:
          path: ./src.zip
          destination: src.zip
