version: 2
jobs:
  build:
    type: approval
    branches:
      only:
        - master
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: Install online dependencies
          command: pip install -r ./requirements.txt -t ./src
      - run:
          name: Install local dependency
          command: pip install ./vrchat-api-python -t ./src
      - run:
          name: Compress src/
          command: |
            apk add zip
            zip -r src src
            ls
      - store_artifacts:
          path: ./src.zip
          destination: src.zip
