version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r ./requirements.txt -t ./src
            pip install ./vrchat-api-python -t ./src
      - run:
          name: Compress src/
          command: |
            apk add zip
            cd src
            chmod 755 ./* -R
            zip -r ../src *
      - store_artifacts:
          path: ./src.zip
          destination: src.zip
      - run:
          name: Release
          command: |
            apk add git
            apk add go=1.9
            go get github.com/tcnksm/ghr
            VERSION=$(git describe)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./src.zip
