version: 2
jobs:
  build:
    docker:
      - image: python:3-slim
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r ./requirements.txt -t ./src
            pip install ./vrchat-api-python -t ./src
      - run:
          name: Update apt-get
          command: |
            echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
            apt-get update
      - run:
          name: Compress src/
          command: |
            apt-get install -y zip
            cd src
            chmod 755 ./* -R
            zip -r /tmp/workspace/src *
      - store_artifacts:
          path: /tmp/workspace/src.zip
          destination: src.zip
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
          - src.zip
  release:
    docker:
      - image: python:3-slim
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Release
          command: |
            apt-get -t stretch-backports install -y git golang
            export GOPATH=$HOME/go
            export PATH="$PATH:$GOPATH/bin"
            go get github.com/tcnksm/ghr
            VERSION=$(git describe)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/workspace/src.zip
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - release:
          requires:
          - hold
