version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: python:3-slim
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r ./requirements.txt -t ./src
            pip install ./vrchat-api-python -t ./src
      - run:
          name: Update apt-get
          command: |
            echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
            apt-get update
      - run:
          name: Compress src/
          command: |
            apt-get install -y zip
            cd src
            chmod 755 ./* -R
            zip -r ../src *
      - store_artifacts:
          path: ./src.zip
          destination: src.zip
      - run:
          name: Release
          command: |
            apt-get -t stretch-backports install -y git golang
            export GOPATH=$HOME/go
            go get github.com/tcnksm/ghr
            VERSION=$(git describe)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./src.zip
